dz-component-calendar
js-tasks-ru/htmlcss-20220414_ruslangr pull request #10
Opened 2022-05-11 18:39 UTC by notRuslan

2022-05-11 18:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-11 19:03 UTC, GSemikozov requested changes

2022-05-11 19:03 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__selected-from, .calendar__selected-to{
.calendar__item_selected-from, .calendar__item_selected-to

2022-05-11 19:03 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__selected-range{
.calendar__item_selected-range

2022-05-13 15:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-15 15:14 UTC, GSemikozov approved these changes

2022-05-15 15:14 UTC, merged