add dz-checkbox
js-tasks-ru/htmlcss-20220414_ruslangr pull request #18
Opened 2022-05-24 10:49 UTC by notRuslan

2022-05-24 10:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-24 19:10 UTC, GSemikozov requested changes

2022-05-24 19:10 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_icon {
наверно все-таки .checkbox__icon?

2022-05-24 19:16 UTC, notRuslan commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_icon {
Конечно.

2022-06-05 10:51 UTC, GSemikozov approved these changes

2022-06-05 10:51 UTC, merged