Dz toggler
js-tasks-ru/htmlcss-20220414_ruslangr pull request #20
Opened 2022-05-24 19:35 UTC by notRuslan

2022-05-24 19:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-24 19:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-25 08:50 UTC, GSemikozov requested changes

2022-05-25 08:50 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio {
в этом ПР смотрим радио или тогл?)

2022-05-25 09:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-25 09:53 UTC, notRuslan commented on 07-lection5/02-radio/radio.css
> +.radio {
togger. Тут повторится код от radio .

2022-05-25 11:20 UTC, GSemikozov approved these changes

2022-05-25 11:20 UTC, merged