add Component card
js-tasks-ru/htmlcss-20220414_ruslangr pull request #4
Opened 2022-04-27 17:52 UTC by notRuslan

не уверен, что у карт нужно было сделать фиксированный размер.

2022-04-27 17:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 19:18 UTC, GSemikozov requested changes

2022-04-27 19:18 UTC, GSemikozov commented on components/card/card.css
> +  margin-left: 30px;
марджины на уровне блока не задаем, здесь нужно работать через родителя (элемент, в который встраиваются карточки), возможно через классы-миксы

2022-04-27 19:18 UTC, GSemikozov commented on components/card/card.css
> +  height: 282px;
эту часть не стоит фиксировать по высоте

2022-04-27 19:18 UTC, GSemikozov commented on components/card/card.css
> +  height: 85px;
и тут

2022-04-27 19:18 UTC, GSemikozov commented on components/card/card.css
> +  box-shadow: 0px 2px 4px rgba(33, 36, 41, 0.05);
в карте не хватает внутренних отступов

2022-04-28 10:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-28 10:12 UTC, notRuslan commented on components/card/card.css
> +  margin-left: 30px;
Сделал через классы-миксы. По другому не придумал.

2022-04-30 17:13 UTC, GSemikozov requested changes

2022-04-30 17:13 UTC, GSemikozov commented on components/preview/preview.css
> +  margin-top: -30px;
лишнее - не стоит здесь применять отрицательные отступы

2022-04-30 17:13 UTC, GSemikozov commented on components/preview/preview.css
> +.preview__card{
на лекции мы обсуждали куда более приятные решения, советую пересмотреть)

2022-04-30 17:13 UTC, GSemikozov commented on components/card/card.css
> +  width: 298px;
таким образом ширину и высоту карточки точно не надо фиксировать - это как минимум расходится с макетом

2022-05-15 15:10 UTC, GSemikozov approved these changes

2022-05-15 15:10 UTC, merged