add skeleton
js-tasks-ru/htmlcss-20220414_ruslangr pull request #8
Opened 2022-05-04 07:33 UTC by notRuslan

По ошибке сделал пуш без комита.

2022-05-04 07:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-04 07:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-04 10:50 UTC, GSemikozov requested changes

2022-05-04 10:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 100%;
вот здесь как раз подойдет flex-grow: 1

2022-05-04 10:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.c-line {
сейчас этот элемент описан как отдельный блок. Правильно вот так - .skeleton__line

2022-05-04 10:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.c-line_short{
.skeleton__line_short - и ниже по аналогии

2022-05-04 13:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-04 13:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-15 15:13 UTC, GSemikozov approved these changes

2022-05-15 15:13 UTC, merged